-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 14:16:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`bd_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bd_cadastro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `celular` VARCHAR(45) NULL,
  `placa_mae` VARCHAR(45) NULL,
  `placa_video` VARCHAR(45) NULL,
  `fonte` VARCHAR(45) NULL,
  `ram` VARCHAR(45) NULL,
  `processador` VARCHAR(45) NULL,
  `acessorios` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `data_entrada` VARCHAR(45) NULL,
  `data_saida` VARCHAR(45) NULL,
  `orcamento` VARCHAR(45) NULL,
  `observacoes` VARCHAR(45) NULL,
  `valor_total` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
